baseURL = 'http://csierniid.github.io/'
languageCode = 'ja'
title = 'COVID-19疫学研究'
contentDir = 'post'
disableKinds = ["RSS", "sitemap"]
theme = "ananke"
publishDir = "docs" 
[taxonomies]
tag = "tags"

